### PR TITLE
Fix modular tree validation limits

### LINKED ISSUE #661: Tree height limit is not enforced
Moreover, property range checking uses more memory than necessary.

See https://github.com/libjxl/jxl-rs/pull/647#issuecomment-3804181708.

### PR DESCRIPTION
**Pull request by hjanuschka**
Fixes #661.

- Enforce the spec tree height limit (2048)
- Avoid allocating num_properties * tree_size property ranges (now O(num_properties))

### CODE REVIEW

File: jxl/src/frame/modular/tree.rs [hunk 1]
```diff
@@ -357,50 +359,109 @@ impl Tree {
...
-        let num_properties = max_property as usize + 1;
-        let mut property_ranges = Vec::new_with_capacity(num_properties * tree.len())?;
-        property_ranges.resize(num_properties * tree.len(), (i32::MIN, i32::MAX));
-        let mut height = Vec::new_with_capacity(tree.len())?;
-        height.resize(tree.len(), 0);
-        for i in 0..tree.len() {
-            const HEIGHT_LIMIT: usize = 2048;
-            if height[i] > HEIGHT_LIMIT {
-                return Err(Error::TreeTooLarge(height[i], HEIGHT_LIMIT));
+        // Validate tree height and property ranges.
```
Comment (veluca93) [inline jxl/src/frame/modular/tree.rs]: What do you think of moving this in a separate function?

File: jxl/src/frame/modular/tree.rs [hunk 2]
```diff
@@ -357,50 +359,109 @@ impl Tree {
...
-            } = tree[i]
-            {
-                height[left as usize] = height[i] + 1;
-                height[right as usize] = height[i] + 1;
-                for p in 0..num_properties {
-                    if p == property as usize {
-                        let (l, u) = property_ranges[i * num_properties + p];
+
+            let mut stack = Vec::new();
+            stack.push(Frame {
```
Comment (veluca93) [inline jxl/src/frame/modular/tree.rs]: Can you add a comment explaining what this code is doing? Not sure how much a future reader is likely to understand the (nice) approach here to use O(num_properties + height) memory. While in some sense it is relatively standard, it is not _incredibly_ so.

On a related note, I don't believe we need `has_split`, and I think it would be nice to use a local enum for the three stages.

File: jxl/src/frame/modular/tree.rs [hunk 3]
```diff
@@ -357,54 +357,129 @@ impl Tree {
         }
         tree_reader.check_final_state(&tree_histograms, br)?;
 
-        let num_properties = max_property as usize + 1;
-        let mut property_ranges = Vec::new_with_capacity(num_properties * tree.len())?;
-        property_ranges.resize(num_properties * tree.len(), (i32::MIN, i32::MAX));
-        let mut height = Vec::new_with_capacity(tree.len())?;
-        height.resize(tree.len(), 0);
-        for i in 0..tree.len() {
+        // Validate tree height and property ranges.
```
Comment (veluca93) [inline jxl/src/frame/modular/tree.rs]: Can you move the function the top level in the file, instead of nesting it?

**Review by veluca93 — APPROVED** [review]
