### PR TITLE
Made frame indices seed the rng

### LINKED ISSUE #424: Discrepancy between libjxl concerning decode to APNG
JXL:
Image

libjxl (djxl) decode:
Image

jxl-rs (jxl_cli) decode (original file fails upload, but all frames appear identical):
[hbo.jxl-rs_20251030.zip](https://github.com/user-attachments/files/23248890/hbo.jxl-rs_20251030.zip)

Image source unknown.

### PR DESCRIPTION
**Pull request by zond**
Fixes #424

### CODE REVIEW

File: jxl/src/frame/decode.rs [hunk 1]
```diff
@@ -365,7 +371,12 @@ impl Frame {
             let x0 = gx * upsampling * group_dim;
             let y0 = gy * upsampling * group_dim;
             // TODO(sboukortt): actual frame indices for the first two
```
Comment (sboukortt) [inline jxl/src/frame/decode.rs]: This change obsoletes the TODO, doesn’t it?
