### PR TITLE
Fixed the offset in spline rendering.

### LINKED ISSUE #157: failing arbtest for splines_consistency
tro repro at  f0a3ed766691014412d65b92f553f3478e3a274d

```
ARBTEST_SEED=0xe9c73bbd00010000 cargo test render::stages::splines::test::splines_consistency


running 1 test
test render::stages::splines::test::splines_consistency ... FAILED

failures:

---- render::stages::splines::test::splines_consistency stdout ----

thread 'render::stages::splines::test::splines_consistency' panicked at jxl/src/features/spline.rs:557:23:
index out of bounds: the len is 70 but the index is 94
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

arbtest failed!
    Seed: 0xe9c73bbd00010000




failures:
    render::stages::splines::test::splines_consistency

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 370 filtered out; finished in 0.57s
```

### PR DESCRIPTION
**Pull request by zond**
Subtracted the row x0 from the pixel to render to avoid trying to render outside the buffer.

Should fix #157.

### CODE REVIEW

**Review by mo271 — APPROVED** [review]

File: jxl/src/features/spline.rs [hunk 1]
```diff
@@ -520,26 +520,33 @@ impl Splines {
...
         xsize: usize,
         segment: &SplineSegment,
     ) {
-        let (x0, y) = position;
+        let (x0, y) = row_pos;
         let x1 = x0 + xsize;
         let clamped_x0 = x0.max((segment.center_x - segment.maximum_distance).round() as usize);
         // one-past-the-end
         let clamped_x1 = x1.min((segment.center_x + segment.maximum_distance).round() as usize + 1);
+        println!(
```
Comment (veluca93) [inline jxl/src/features/spline.rs:532]: Should this stay here?

Comment (zond) [reply jxl/src/features/spline.rs:532]: Eeeh... I'll send a patch :p
