### PR TITLE
Fix spline DISTANCE_EXP to match libjxl default

### LINKED ISSUE #431: Discrepancy between libjxl concerning spline rendering in XYB
JXL:
Image

djxl decode:
Image

jxl_cli decode:
Image

Source:
[map.txt](https://github.com/user-attachments/files/23263113/map.txt)

### PR DESCRIPTION
**Pull request by hjanuschka**
Use DISTANCE_EXP=3.0 by default instead of 5.0 to match libjxl's non-high-precision mode.

Adds `high_precision` option to `JxlDecoderOptions` for integrators who need the higher precision behavior.

Fixes #431

### CODE REVIEW

File: jxl/src/api/options.rs [hunk 1]
```diff
@@ -26,6 +26,10 @@ pub struct JxlDecoderOptions {
     pub xyb_output_linear: bool,
     pub enable_output: bool,
     pub cms: Option<Box<dyn JxlCms>>,
+    /// Use high precision mode for spline rendering.
+    /// When false (default), uses lower precision settings that match libjxl's default.
+    /// When true, uses higher precision at the cost of performance.
+    pub high_precision: bool,
```
Comment (veluca93) [inline jxl/src/api/options.rs:35]: Just a nit, but in libjxl JXL_HIGH_PRECISION is used also for other decisions, not just for spline rendering - we might want to have the documentation reflect that (i.e. I plan to have high_precision control whether some intermediate buffers could be saved as f16)

Comment (hjanuschka) [reply jxl/src/api/options.rs:35]: documentation updated, should i give it a try to add control as you mentioned (or should this be a separate PR)?

Comment (veluca93) [reply jxl/src/api/options.rs:35]: No, this is fine for now.
